language: ruby
rvm:
  - 2.1.3

bundler_args: --without development

before_script:
  - psql -c 'create database publichub_test;' -U postgres

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test