default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: publichub_development

test: &test
  <<: *default
  database: publichub_test

production:
  <<: *default
  database: publichub_production
  host: localhost

cucumber:
  <<: *test